apiVersion: v1 
kind: Pod
metadata: 
   name: secrets-demo
spec:
   containers:
    - name: nginx
      image: nginx
      envFrom:
      - secretRef:
         name: pod-secret


#secret's store in ssm parameter or secretmanager's.


#basic  configuration option's.
